name: Locust Load Test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r loadrequirements.txt

      - name: Run Locust tests
        run: |
          cd tests
          locust -f locustfile.py --headless -u 10 -r 2 --run-time 1m --csv=../reports/test_results
